### ISSUE TITLE
Email sending somewhat broken

### ISSUE THREAD

**Issue by TKasekamp** [JaanJanno/ConsultationWeb#125]
When setting a meeting, the server is unable to respond and this error message is displayed.

`2016-11-24 22:34:32.653 ERROR 5748 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.ut.ee, 25; timeout -1;
  nested exception is:
	java.net.SocketException: Permission denied: connect. Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.ut.ee, 25; timeout -1;
  nested exception is:
	java.net.SocketException: Permission denied: connect; message exceptions (1) are:
Failed message 1: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: mail.ut.ee, 25; timeout -1;
  nested exception is:
	java.net.SocketException: Permission denied: connect] with root cause`

**Comment by TKasekamp** [comment]
When setting meeting in Heroku, the following error message is displayed: 

```
2016-11-25T21:01:27.512115+00:00 app[web.1]: 2016-11-25 21:01:27.511 ERROR 4 --- [nio-7504-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.mail.MailSendException: Failed messages: javax.mail.SendFailedException: Invalid Addresses;
2016-11-25T21:01:27.512126+00:00 app[web.1]:   nested exception is:
2016-11-25T21:01:27.512128+00:00 app[web.1]:    com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <toniskasekamp@gmail.com>: Relay access denied
2016-11-25T21:01:27.512128+00:00 app[web.1]: ; message exceptions (1) are:
2016-11-25T21:01:27.512129+00:00 app[web.1]: Failed message 1: javax.mail.SendFailedException: Invalid Addresses;
2016-11-25T21:01:27.512130+00:00 app[web.1]:   nested exception is:
2016-11-25T21:01:27.512131+00:00 app[web.1]:    com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <toniskasekamp@gmail.com>: Relay access denied
2016-11-25T21:01:27.512131+00:00 app[web.1]: ] with root cause
2016-11-25T21:01:27.512132+00:00 app[web.1]:
2016-11-25T21:01:27.512133+00:00 app[web.1]: org.springframework.mail.MailSendException: Failed messages: javax.mail.SendFailedException: Invalid Addresses;
2016-11-25T21:01:27.512134+00:00 app[web.1]:   nested exception is:
2016-11-25T21:01:27.512137+00:00 app[web.1]:    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:307) ~[spring-context-support-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2016-11-25T21:01:27.512134+00:00 app[web.1]:    com.sun.mail.smtp.SMTPAddressFailedException: 554 5.7.1 <toniskasekamp@gmail.com>: Relay access denied
2016-11-25T21:01:27.512139+00:00 app[web.1]:    at ee.avok.consultation.service.EmailServiceImpl.send(EmailServiceImpl.java:39) ~[consultation-0.0.2.jar!/:0.0.2]
2016-11-25T21:01:27.512140+00:00 app[web.1]:    at ee.avok.consultation.service.EmailServiceImpl.sendReminder(EmailServiceImpl.java:23) ~[consultation-0.0.2.jar!/:0.0.2]
2016-11-25T21:01:27.512135+00:00 app[web.1]:
2016-11-25T21:01:27.512141+00:00 app[web.1]:    at ee.avok.consultation.service.ConsultationServiceImpl.setConsultationDate(ConsultationServiceImpl.java:163) ~[consultation-0.0.2.jar!/:0.0.2]
2016-11-25T21:01:27.512136+00:00 app[web.1]:    at org.springframework.mail.javamail.JavaMailSenderImpl.doSend(JavaMailSenderImpl.java:474) ~[spring-context-support-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2016-11-25T21:01:27.512138+00:00 app[web.1]:    at org.springframework.mail.javamail.JavaMailSenderImpl.send(JavaMailSenderImpl.java:296) ~[spring-context-support-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2016-11-25T21:01:27.512152+00:00 app[web.1]:    at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:743) ~[spring-webmvc-4.2.7.RELEASE.jar!/:4.2.7.RELEASE]
2016-11-25T21:01:27.512142+00:00 app[web.1]:    at ee.avok.consultation.controller.RequestController.postSetMeetingPage(RequestController.java:178) ~[consultation-0.0.2.jar!/:0.0.2]
```

**Comment by JaanJanno** [comment]
This seems to come from Heroku not being on UT network. Will be able to fix when customer sends email credentials.

**Comment by JaanJanno** [comment]
Closing, as the email service works as expected without password.
Can add support for other domains when given credentials by customer.
